### PR TITLE
upgrading major dependencies versions

### PR DESCRIPTION
**Pull request by mjburghoffer**

### CODE REVIEW

**Comment by christydennison** [comment]
LGTM once tested with RIQ

**Comment by christydennison** [comment]
Also if you don't update soa-boilerplate first, next time someone uses boilerplate they'll wipe out these changes

**Comment by mjburghoffer** [comment]
@christydennison i've been updating boilerplate as i've been going along.  What do you mean when you say "test with riq"?

**Comment by christydennison** [comment]
Awesome, good to hear. I didn't get a PR so I wasn't aware. When you bump RIQ's version of SOA, does everything still work?

**Comment by mjburghoffer** [comment]
@christydennison @jontg  I was unaware of how tightly coupled riq is with soa.  As graph does not work with the riq codebase at all, I think going forward after this change graph should fork SOA so it doesn't interfere with riq.  I don't want to have to check if riq builds/works when changing anything related to graph.

**Pull request merged**
